SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS GAME_ASIGN;
DROP TABLE IF EXISTS GAME_HISTORY_CHANGE_LOG;
DROP TABLE IF EXISTS GAME_HISTORY;
DROP TABLE IF EXISTS MEMBER_RATE_CHANGE_LOG;
DROP TABLE IF EXISTS MEMBER_RATE;
DROP TABLE IF EXISTS MEMBER_CHANGE_LOG;
DROP TABLE IF EXISTS MEMBER_ALIAS;
DROP TABLE IF EXISTS MEMBER_ATTRIBUTE_CHANGE_LOG;
DROP TABLE IF EXISTS MEMBER_ATTRIBUTE;
DROP TABLE IF EXISTS MEMBER_SECURITY;
DROP TABLE IF EXISTS MEMBER;




/* Create Tables */

CREATE TABLE GAME_ASIGN
(
	GAME_ASIGN bigint NOT NULL AUTO_INCREMENT,
	MEMBER_ID bigint NOT NULL,
	GAME_HISTORY_ID bigint NOT NULL,
	TEAM_NUMBER int NOT NULL,
	IS_WIN boolean NOT NULL,
	CHANGE_REATE int NOT NULL,
	PRIMARY KEY (GAME_ASIGN)
);


CREATE TABLE GAME_HISTORY
(
	GAME_HISTORY_ID bigint NOT NULL AUTO_INCREMENT,
	HOST_MEBER_ID bigint NOT NULL,
	GAME_NAME varchar(1024) NOT NULL,
	NAISEN_TYPE char(16) NOT NULL,
	GAME_TYPE char(16) NOT NULL,
	FILLED_DATETIME datetime NOT NULL,
	FINISH_DATETIME datetime NOT NULL,
	WIN_TEAM_NUMBER int NOT NULL,
	END_STATUS char(3) NOT NULL,
	PRIMARY KEY (GAME_HISTORY_ID)
);


CREATE TABLE GAME_HISTORY_CHANGE_LOG
(
	GAME_HISTORY_CHANGE_LOG bigint NOT NULL AUTO_INCREMENT,
	GAME_HISTORY_ID bigint NOT NULL,
	HOST_MEMBER_ID bigint NOT NULL,
	GAME_NAME varchar(1024) NOT NULL,
	NAISEN_TYPE char(16) NOT NULL,
	GAME_TYPE char(16) NOT NULL,
	FILLED_DATETIME datetime NOT NULL,
	FINISH_DATETIME datetime NOT NULL,
	WIN_TEAM_NUMBER int NOT NULL,
	END_STATUS char(3) NOT NULL,
	CHANGE_DATE datetime NOT NULL,
	CHANGE_REASON varchar(1024) NOT NULL,
	PRIMARY KEY (GAME_HISTORY_CHANGE_LOG)
);


CREATE TABLE MEMBER
(
	MEMBER_ID bigint NOT NULL AUTO_INCREMENT,
	-- 登録名はユーザ側で変更させない仕様にするため、こちらのテーブルに持ちます。
	REGISTER_NAME char(255) NOT NULL COMMENT '登録名はユーザ側で変更させない仕様にするため、こちらのテーブルに持ちます。',
	MEMBER_STATUS char(3) NOT NULL,
	PRIMARY KEY (MEMBER_ID),
	UNIQUE (REGISTER_NAME)
);


CREATE TABLE MEMBER_ALIAS
(
	MEMBER_ALIAS_ID bigint NOT NULL AUTO_INCREMENT,
	MEMBER_ID bigint NOT NULL,
	ALIAS_NAME char(255) NOT NULL,
	PRIMARY KEY (MEMBER_ALIAS_ID),
	UNIQUE (MEMBER_ID),
	UNIQUE (ALIAS_NAME)
);


CREATE TABLE MEMBER_ATTRIBUTE
(
	MEMBER_ATTRIBUTE_ID bigint NOT NULL AUTO_INCREMENT,
	MEMBER_ID bigint NOT NULL,
	PRIMARY KEY (MEMBER_ATTRIBUTE_ID),
	UNIQUE (MEMBER_ID)
);


CREATE TABLE MEMBER_ATTRIBUTE_CHANGE_LOG
(
	MEMBER_ATTRIBUTE_CHANGE_LOG_ID bigint NOT NULL AUTO_INCREMENT,
	MEMBER_ATTRIBUTE_ID bigint NOT NULL,
	CHANGE_DATE datetime NOT NULL,
	CHANGE_REASON varchar(1024) NOT NULL,
	PRIMARY KEY (MEMBER_ATTRIBUTE_CHANGE_LOG_ID)
);


CREATE TABLE MEMBER_CHANGE_LOG
(
	MEMBER_CHANGE_LOG bigint NOT NULL AUTO_INCREMENT,
	MEMBER_ID bigint NOT NULL,
	REGISTER_NAME char(255) NOT NULL,
	MEMBER_STATUS char(3) NOT NULL,
	CHANGE_DATE datetime NOT NULL,
	CHANGE_REASON varchar(1024) NOT NULL,
	PRIMARY KEY (MEMBER_CHANGE_LOG)
);


CREATE TABLE MEMBER_RATE
(
	MEMBER_RATE_ID bigint NOT NULL AUTO_INCREMENT,
	MEMBER_ID bigint NOT NULL,
	GAME_TYPE char(16) NOT NULL,
	RATE bigint NOT NULL,
	PRIMARY KEY (MEMBER_RATE_ID),
	UNIQUE (MEMBER_ID)
);


CREATE TABLE MEMBER_RATE_CHANGE_LOG
(
	MEMBER_RATE_CHANGE_LOG_ID bigint NOT NULL AUTO_INCREMENT,
	MEMBER_RATE_ID bigint NOT NULL,
	GAME_TYPE char(16) NOT NULL,
	RATE bigint NOT NULL,
	CHANGE_DATE datetime NOT NULL,
	CHANGE_REASON varchar(1024) NOT NULL,
	PRIMARY KEY (MEMBER_RATE_CHANGE_LOG_ID)
);


CREATE TABLE MEMBER_SECURITY
(
	MEMBER_SECURITY_ID bigint NOT NULL AUTO_INCREMENT,
	MEMBER_ID bigint NOT NULL,
	PASSWORD varchar(2100) NOT NULL,
	PRIMARY KEY (MEMBER_SECURITY_ID),
	UNIQUE (MEMBER_ID)
);



/* Create Foreign Keys */

ALTER TABLE GAME_ASIGN
	ADD FOREIGN KEY (GAME_HISTORY_ID)
	REFERENCES GAME_HISTORY (GAME_HISTORY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GAME_HISTORY_CHANGE_LOG
	ADD FOREIGN KEY (GAME_HISTORY_ID)
	REFERENCES GAME_HISTORY (GAME_HISTORY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GAME_ASIGN
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_RATE
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_CHANGE_LOG
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_ALIAS
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_ATTRIBUTE
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GAME_HISTORY
	ADD FOREIGN KEY (HOST_MEBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_SECURITY
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_ATTRIBUTE_CHANGE_LOG
	ADD FOREIGN KEY (MEMBER_ATTRIBUTE_ID)
	REFERENCES MEMBER_ATTRIBUTE (MEMBER_ATTRIBUTE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_RATE_CHANGE_LOG
	ADD FOREIGN KEY (MEMBER_RATE_ID)
	REFERENCES MEMBER_RATE (MEMBER_RATE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



